name: Build and Deploy

on:
  push:
    branches:
      - main

  workflow_dispatch:
    
env:
  REPO_NAME: ${{ github.event.repository.name }}

jobs:   
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Publish Blazor WebAssembly app
        run: dotnet publish ./${{ env.REPO_NAME }}/${{ env.REPO_NAME }}.csproj -c Release -o release

      - name: Install dotnet-serve
        run: dotnet tool install --global dotnet-serve

      - name: Add .NET tools to PATH
        run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH
        
      - name: Start local server
        run: |
          dotnet-serve -d release/wwwroot -p 5000 --quiet &
          sleep 5

      - name: Install Playwright Chromium Browser
        run: npx playwright install chromium --with-deps

      - name: Run Playwright UI tests
        run: dotnet test ${{ env.REPO_NAME }}/${{ env.REPO_NAME }}.PlaywrightTests.csproj
        env:
          BaseUrl: http://localhost:5000
          PATH: $PATH:$HOME/.dotnet/tools
  
  package:
    needs: build
    runs-on: ubuntu-latest
      
    steps:
    - name: Update Base Url in index.html - Local Dev workaround
      run: sed -i 's/<base href="\/" \/>/<base href="\/${{ env.REPO_NAME }}\/" \/>/g' release/wwwroot/index.html

    - name: Copy index.html to 404.html - GitHub Pages routing workaround
      run: cp release/wwwroot/index.html release/wwwroot/404.html

    - name: Upload static files as artifact
      id: deployment
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./release/wwwroot

#  deploy:
#    needs: package
#    runs-on: ubuntu-latest
#
#    permissions:
#      pages: write
#      id-token: write
#
#    environment:
#      name: github-pages
#      url: ${{ steps.deployment.outputs.page_url }}
#
#    steps:
#      - name: Deploy to GitHub Pages
#        id: deployment
#        uses: actions/deploy-pages@v4
